# if(! require(DBI)) install.packages('DBI')
if(! require(knitr)) install.packages('knitr')
if(! require(rmdformats)) install.packages('rmdformats')
if(! require(DT)) install.packages('DT')
if(! require(tidyr)) install.packages('tidyr')
if(! require(lubridate)) install.packages('lubridate')
if(! require(stringr)) install.packages('stringr')
if(! require(data.table)) install.packages('data.table')
if(! require(magrittr)) install.packages('magrittr')
if(! require(dplyr)) install.packages('dplyr')
if(! require(readr)) install.packages('readr')
if(! require(bigrquery)) install.packages('bigrquery')
if(! require(highcharter)) install.packages('highcharter')
if(! require(kableExtra)) install.packages('kableExtra')
if(! require(ggplot2)) install.packages('ggplot2')